name: Airdrop Bot
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install farcaster requests python-dotenv

      - name: Run Bot
        env:
          # Make sure these match the names in your "Secrets" settings
          WARPCAST_MNEMONIC: ${{ secrets.WARPCAST_MNEMONIC }}
          WARPCAST_ID: ${{ secrets.WARPCAST_ID }}
        run: python bot.py
